name: Build Nightly Plugin

on:
  workflow_dispatch:
  push:
    paths:
      - "scripting/**"
  pull_request:
    paths:
      - "scripting/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-latest
          - windows-2019
          - windows-latest
        sm_version:
          - "1.11"
          - "latest"

        include:
          - sm_version: latest
            sm_branch: master

          - sm_version: "1.11"
            sm_branch: "1.11-dev"

          - os: windows-latest
            os_short: win

          - os: ubuntu-latest
            os_short: linux

          - os: windows-2019
            os_short: win-2019

          - os: ubuntu-latest
            os_short: linux-debian11

    steps:
      - uses: actions/checkout@v3
      - name: Build sourcemod plugin
        uses: maxime1907/action-sourceknight@v1
        with:
          cmd: build

      - name: Create package
        run: |
          mkdir -p /tmp/package
          cp -R .sourceknight/package/* /tmp/package
          cp -R game/addons/sourcemod/translations /tmp/package/common/addons/sourcemod/

      - name: Upload build archive
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: /tmp/package
