name: Nightly Build

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - "scripting/**"
  pull_request:
    paths:
      - "scripting/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        sm_version:
          - "1.11"
          - "1.12"

    steps:
      - name: Get current date
        id: date
        run: echo "{name}={$(date +'%Y%m%d%H%M')}" >> $GITHUB_OUTPUT
        
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Checkout sm-ext-discord
        uses: actions/checkout@v4
        with:
          repository: Enovale/sm-ext-discord
          path: sm-ext-discord

      - name: Checkout Steamworks
        uses: actions/checkout@v4
        with:
          repository: KyleSanderson/SteamWorks
          path: steamworks

      - name: Checkout log4sp
        uses: actions/checkout@v4
        with:
          repository: F1F88/sm-ext-log4sp
          path: sm-ext-log4sp

      - name: Checkout chat-processor
        uses: actions/checkout@v4
        with:
          repository: KeithGDR/chat-processor
          path: chat-processor

      - name: Download morecolors
        uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
        id: downloadfile
        with:
          url: "https://github.com/DoctorMcKay/sourcemod-plugins/raw/refs/heads/master/scripting/include/morecolors.inc"
          target: plugin/scripting/include/

      - name: Checkout sourcebans-pp
        uses: actions/checkout@v4
        with:
          repository: sbpp/sourcebans-pp
          path: sourcebans-pp

      - name: Checkout updater
        uses: actions/checkout@v4
        with:
          repository: nukkonyan/Updater
          path: updater

      - name: Copy includes
        run: |
          cp -R sm-ext-discord/scripting/include/** plugin/scripting/include/
          cp -R steamworks/Pawn/includes/** plugin/scripting/include/
          cp -R sm-ext-log4sp/sourcemod/scripting/include/** plugin/scripting/include/
          cp -R chat-processor/scripting/include/** plugin/scripting/include/
          cp -R sourcebans-pp/game/addons/sourcemod/scripting/include/** plugin/scripting/include/
          cp -R updater/scripting/include/** plugin/scripting/include/

      - name: Compile My plugin
        uses: SheplyRam/compile-sourcemod-plugin@v1
        with:
          sourcemod: ${{ matrix.sm_version }}
          input: 'plugin/scripting/yadr.sp'
          output: '/tmp/package/addons/sourcemod/plugins/yadr.smx'
          includes: 'plugin/scripting/include/ plugin/scripting/'

      - name: Create package
        run: |
          cp -R plugin/translations /tmp/package/addons/sourcemod/

      - name: Upload build archive
        uses: actions/upload-artifact@v4
        with:
          name: yadr-nightly-sm${{ matrix.sm_version }}-v${{ steps.date.outputs.date }}
          path: /tmp/package
