name: Draft Release Candidate

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Version tag for new release'
        required: true
      prerelease:
        type: boolean
        description: 'Release is prerelease'
        default: false
        required: true

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v9
        with:
          skip_unpack: true
          workflow: ci.yml
          path: yadr-${{ github.event.inputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename artifacts
        run: |
          cd yadr-${{ github.event.inputs.tag }}
          ls -R
          mv *1.12* yadr-sm1.12-v${{ github.event.inputs.tag }}.zip

      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.tag }}
          draft: true
          prerelease: ${{ github.event.inputs.prerelease == 'true' }}
          artifactErrorsFailBuild: true
          artifactContentType: application/zip
          artifacts: "yadr-${{ github.event.inputs.tag }}/*.zip"
          body: "PLEASE FILL IN WITH CHANGELOG!"
