name: Draft Release Candidate

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Version tag for new release'
        required: true

jobs:
  build:
    uses: ./.github/workflows/ci.yml
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: [build]
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v9
        with:
          skip_unpack: true
          workflow: ci.yml
          path: yadr-${{ github.event.inputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display structure of downloaded files
        run: ls -R yadr-${{ github.event.inputs.tag }}

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yadr-${{ github.event.inputs.tag }}/yadr-sm1.11-*
          asset_name: yadr-sm1.11-yadr-${{ github.event.inputs.tag }}.zip
          asset_content_type: application/zip

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yadr-${{ github.event.inputs.tag }}/yadr-sm1.12-*
          asset_name: yadr-sm1.12-yadr-${{ github.event.inputs.tag }}.zip
          asset_content_type: application/zip
